import '@/globals.css';
import '@mantine/core/styles.css';
import { ColorSchemeScript } from '@mantine/core';

import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import MantineProviderServer from '@/styles/mantine/MantineProviderServer';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={nunito.className}>
        <MantineProviderServer>{children}</MantineProviderServer>
      </body>
    </html>
  );
}
